// WARNING: THE USAGE OF CUSTOM SCRIPTS IS NOT SUPPORTED. VTEX IS NOT LIABLE FOR ANY DAMAGES THIS MAY CAUSE. THIS MAY BREAK YOUR STORE AND STOP SALES. IN CASE OF ERRORS, PLEASE DELETE THE CONTENT OF THIS SCRIPT.

// ALTERAR A COR DO ITEM DE PAGAMENTO

$(document).ready(function () {
    if ($(location).attr('href')){
        $('li.prog-payment').addClass('prog-id')    
    }
});